//! Cross-implementation compatibility: the Rust core against the web client.
//!
//! `tests/fixtures/sbq2-vectors.json` is generated by the WEB implementation
//! (`src/network/descriptor/sbq2.js` and `keyexchange.js` in the securebit-chat
//! repo). Every value here must be reproduced byte for byte.
//!
//! This is not a nice-to-have. A desktop user scans a QR code from a browser and
//! the two hash the same bytes into the same transcript; one byte of divergence
//! is not a graceful degradation, it is two peers computing different safety
//! codes and refusing to trust each other.

use securebit_core::descriptor::{
    self, Descriptor, DescriptorType, EncodeParams, SdpFields,
};
use securebit_core::keyexchange::{self, Role};
use serde_json::Value;

fn vectors() -> Value {
    let raw = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/sbq2-vectors.json"))
        .expect("vectors file missing — regenerate it from the web repo");
    serde_json::from_str(&raw).expect("vectors file is not valid JSON")
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
}
fn hex(b: &[u8]) -> String { b.iter().map(|x| format!("{:02x}", x)).collect() }

fn fields_from(d: &Descriptor, priorities_from: &SdpFields) -> SdpFields {
    // Candidates decoded from the wire carry no priority (it is not transmitted);
    // re-encoding uses the order as decoded, which is what the encoder wrote.
    let _ = priorities_from;
    SdpFields {
        ufrag: d.ufrag.clone(),
        pwd: d.pwd.clone(),
        fingerprint: d.fingerprint,
        setup: d.setup,
        max_message_size: d.max_message_size,
        candidates: d.candidates.clone(),
    }
}

#[test]
fn decodes_every_web_descriptor() {
    let v = vectors();
    let now = v["expiresAtMs"].as_i64().unwrap() - 60_000;

    for item in v["descriptors"].as_array().unwrap() {
        let name = item["name"].as_str().unwrap();
        let bytes = unhex(item["encodedHex"].as_str().unwrap());

        let d = descriptor::decode_descriptor(&bytes, now)
            .unwrap_or_else(|e| panic!("{name}: web descriptor rejected by the Rust decoder: {e:?}"));

        assert_eq!(d.ufrag, item["ufrag"].as_str().unwrap(), "{name}: ufrag");
        assert_eq!(d.pwd, item["pwd"].as_str().unwrap(), "{name}: pwd");
        assert_eq!(hex(&d.fingerprint), item["fingerprintHex"].as_str().unwrap(), "{name}: fingerprint");
        assert_eq!(d.setup as u64, item["setup"].as_u64().unwrap(), "{name}: setup");
        assert_eq!(d.max_message_size as u64, item["maxMessageSize"].as_u64().unwrap(), "{name}: max-message-size");
        assert_eq!(d.candidates.len(), item["prunedCount"].as_u64().unwrap() as usize, "{name}: candidate count");
        let expected_type = if item["type"] == "offer" { DescriptorType::Offer } else { DescriptorType::Answer };
        assert_eq!(d.dtype, expected_type, "{name}: type");
        assert_eq!(d.binding_tag.is_some(), expected_type == DescriptorType::Answer, "{name}: binding tag presence");
        assert!(d.commitment.is_some(), "{name}: commitment must survive");
        assert_eq!(hex(&d.commitment.unwrap()), v["commitmentHex"].as_str().unwrap(), "{name}: commitment value");
    }
}

#[test]
fn text_form_matches_the_web() {
    let v = vectors();
    for item in v["descriptors"].as_array().unwrap() {
        let name = item["name"].as_str().unwrap();
        let bytes = unhex(item["encodedHex"].as_str().unwrap());
        assert_eq!(descriptor::encode_text(&bytes), item["text"].as_str().unwrap(), "{name}: SB2 text form");
        assert_eq!(descriptor::decode_text(item["text"].as_str().unwrap()).unwrap(), bytes, "{name}: text round-trip");
        assert!(descriptor::looks_like_sbq2(item["text"].as_str().unwrap()), "{name}: must be detected as SBQ2");
    }
    // SB1 payloads must not be mistaken for SBQ2 in either direction.
    assert!(!descriptor::looks_like_sbq2("SB1:gz:eJy1"));
    assert!(!descriptor::looks_like_sbq2("SB1:bin:eJy1"));
    assert!(descriptor::decode_text("SB1:gz:eJy1").is_err());
}

#[test]
fn reencoding_reproduces_the_web_bytes() {
    let v = vectors();
    let now = v["expiresAtMs"].as_i64().unwrap() - 60_000;

    for item in v["descriptors"].as_array().unwrap() {
        let name = item["name"].as_str().unwrap();
        let bytes = unhex(item["encodedHex"].as_str().unwrap());
        let d = descriptor::decode_descriptor(&bytes, now).unwrap();
        let fields = fields_from(&d, &descriptor::parse_sdp(item["sdp"].as_str().unwrap()).unwrap());

        let reencoded = descriptor::encode_descriptor(&EncodeParams {
            dtype: d.dtype,
            binding_tag: d.binding_tag,
            expires_at_ms: d.expires_at_ms,
            fields: &fields,
            commitment: d.commitment,
        }).unwrap_or_else(|e| panic!("{name}: re-encode failed: {e:?}"));

        assert_eq!(hex(&reencoded), hex(&bytes), "{name}: Rust must reproduce the web's bytes exactly");
    }
}

#[test]
fn rebuilt_sdp_matches_the_web_serializer() {
    let v = vectors();
    let now = v["expiresAtMs"].as_i64().unwrap() - 60_000;

    for item in v["descriptors"].as_array().unwrap() {
        let name = item["name"].as_str().unwrap();
        let bytes = unhex(item["encodedHex"].as_str().unwrap());
        let d = descriptor::decode_descriptor(&bytes, now).unwrap();
        let rebuilt = descriptor::serialize_sdp(&d);
        assert_eq!(rebuilt, item["rebuiltSdp"].as_str().unwrap(),
                   "{name}: the rebuilt SDP must be identical to the web's, line for line");
    }
}

#[test]
fn parsing_the_same_sdp_yields_the_same_descriptor() {
    // The full path a desktop peer actually takes: parse a browser SDP, prune,
    // encode — and land on the bytes the browser would have produced.
    let v = vectors();
    let expires = v["expiresAtMs"].as_i64().unwrap();
    let commitment: [u8; 16] = unhex(v["commitmentHex"].as_str().unwrap()).try_into().unwrap();
    let binding: [u8; 8] = unhex(v["bindingHex"].as_str().unwrap()).try_into().unwrap();

    for item in v["descriptors"].as_array().unwrap() {
        let name = item["name"].as_str().unwrap();
        let raw = descriptor::parse_sdp(item["sdp"].as_str().unwrap())
            .unwrap_or_else(|e| panic!("{name}: parse_sdp failed: {e:?}"));
        let pruned = descriptor::prune_candidates(&raw.candidates);
        assert_eq!(pruned.len(), item["prunedCount"].as_u64().unwrap() as usize,
                   "{name}: pruning must keep the same candidates as the web");

        let is_answer = item["type"] == "answer";
        let fields = SdpFields { candidates: pruned, ..raw };
        let bytes = descriptor::encode_descriptor(&EncodeParams {
            dtype: if is_answer { DescriptorType::Answer } else { DescriptorType::Offer },
            binding_tag: if is_answer { Some(binding) } else { None },
            expires_at_ms: expires,
            fields: &fields,
            commitment: Some(commitment),
        }).unwrap_or_else(|e| panic!("{name}: encode failed: {e:?}"));

        assert_eq!(hex(&bytes), item["encodedHex"].as_str().unwrap(),
                   "{name}: encoding the same SDP must give the web's exact bytes");
    }
}

#[test]
fn key_exchange_vectors_match() {
    let v = vectors();
    let kx = &v["keyExchange"];
    let ecdh = unhex(kx["ecdhSpkiHex"].as_str().unwrap());
    let ecdsa = unhex(kx["ecdsaSpkiHex"].as_str().unwrap());

    let blob_offer = keyexchange::encode_key_blob(Role::Offer, &ecdh, &ecdsa).unwrap();
    let blob_answer = keyexchange::encode_key_blob(Role::Answer, &ecdh, &ecdsa).unwrap();
    assert_eq!(hex(&blob_offer), kx["blobOfferHex"].as_str().unwrap(), "offer key blob");
    assert_eq!(hex(&blob_answer), kx["blobAnswerHex"].as_str().unwrap(), "answer key blob");

    let decoded = keyexchange::decode_key_blob(&blob_offer).unwrap();
    assert_eq!(decoded.role, Role::Offer);
    assert_eq!(hex(&decoded.ecdh_spki), kx["ecdhSpkiHex"].as_str().unwrap());
    assert_eq!(hex(&decoded.ecdsa_spki), kx["ecdsaSpkiHex"].as_str().unwrap());

    assert_eq!(hex(&descriptor::commit_blob(&blob_offer)), kx["commitOfferBlobHex"].as_str().unwrap(),
               "commitment must match the web's");

    let offer_desc = unhex(v["descriptors"][0]["encodedHex"].as_str().unwrap());
    let answer_desc = unhex(v["descriptors"][1]["encodedHex"].as_str().unwrap());
    assert_eq!(hex(&descriptor::binding_tag(&offer_desc)), kx["bindingTagOfOfferDescHex"].as_str().unwrap(),
               "binding tag must match the web's");

    let transcript = keyexchange::build_transcript(&offer_desc, &answer_desc, &blob_offer, &blob_answer).unwrap();
    assert_eq!(hex(&transcript), kx["transcriptHex"].as_str().unwrap(), "transcript must be byte-identical");
    assert_eq!(hex(&keyexchange::derive_transcript_salt(&transcript)), kx["transcriptSaltHex"].as_str().unwrap(),
               "HKDF salt must match");
    assert_eq!(hex(&keyexchange::proof_payload(&transcript)), kx["proofPayloadHex"].as_str().unwrap(),
               "proof payload must match");

    let shared = unhex(kx["sharedSecretHex"].as_str().unwrap());
    assert_eq!(keyexchange::compute_transcript_sas(&shared, &transcript).unwrap(),
               kx["sas"].as_str().unwrap(),
               "both implementations must show the user the same digits");
}

// ---------------------------------------------------------------------------
// Rejection: the decoder is a parser of hostile input on this side too.
// ---------------------------------------------------------------------------

#[test]
fn rejects_malformed_descriptors() {
    let v = vectors();
    let now = v["expiresAtMs"].as_i64().unwrap() - 60_000;
    let good = unhex(v["descriptors"][0]["encodedHex"].as_str().unwrap());

    assert!(descriptor::decode_descriptor(&[], now).is_err(), "empty");
    assert!(descriptor::decode_descriptor(&good[..good.len() - 1], now).is_err(), "truncated");
    assert!(descriptor::decode_descriptor(&vec![0u8; descriptor::MAX_PAYLOAD_BYTES + 1], now).is_err(), "oversized");

    for bad_version in [0x00u8, 0x01, 0x03, 0xff] {
        let mut x = good.clone(); x[0] = bad_version;
        assert!(descriptor::decode_descriptor(&x, now).is_err(), "version 0x{bad_version:02x}");
    }

    let mut trailing = good.clone(); trailing.extend_from_slice(&[1, 2, 3]);
    assert!(descriptor::decode_descriptor(&trailing, now).is_err(), "trailing bytes");

    let mut reserved_type = good.clone(); reserved_type[1] = (reserved_type[1] & !0x03) | 0x02;
    assert!(descriptor::decode_descriptor(&reserved_type, now).is_err(), "reserved type");

    let mut reserved_setup = good.clone(); reserved_setup[1] |= 0x0c;
    assert!(descriptor::decode_descriptor(&reserved_setup, now).is_err(), "reserved setup role");

    // Expiry, in both directions.
    let expires = v["expiresAtMs"].as_i64().unwrap();
    assert!(descriptor::decode_descriptor(&good, expires + 60_000).is_ok(), "one minute of skew is tolerated");
    assert!(descriptor::decode_descriptor(&good, expires + 3_600_000).is_err(), "well past expiry");

    // ICE credentials: alphabet and control characters.
    let uf_off = 1 + 1 + 3 + descriptor::FINGERPRINT_BYTES;
    for evil in [0x0du8, 0x0a, 0x00, b'!'] {
        let mut x = good.clone(); x[uf_off + 1] = evil;
        assert!(descriptor::decode_descriptor(&x, now).is_err(), "injected byte 0x{evil:02x}");
    }
    let mut short_ufrag = good.clone(); short_ufrag[uf_off] = 2;
    assert!(descriptor::decode_descriptor(&short_ufrag, now).is_err(), "ufrag too short");
}

#[test]
fn rejects_unknown_extension_types() {
    let v = vectors();
    let now = v["expiresAtMs"].as_i64().unwrap() - 60_000;
    // The synthetic vector is the one carrying a TLV record.
    let item = v["descriptors"].as_array().unwrap().iter()
        .find(|d| d["name"].as_str().unwrap().contains("tlv")).expect("tlv vector");
    let good = unhex(item["encodedHex"].as_str().unwrap());
    assert!(descriptor::decode_descriptor(&good, now).is_ok(), "the TLV vector itself must decode");

    // Rewrite the record type: deny by default, never skip.
    let mut unknown = good.clone();
    let n = unknown.len();
    unknown[n - 6] = 0x7f;
    assert!(descriptor::decode_descriptor(&unknown, now).is_err(), "unknown extension type must be refused");

    let mut bad_len = good.clone(); bad_len[n - 5] = 3;
    assert!(descriptor::decode_descriptor(&bad_len, now).is_err(), "wrong TLV length");
}

#[test]
fn rejects_malformed_key_blobs() {
    let v = vectors();
    let good = unhex(v["keyExchange"]["blobOfferHex"].as_str().unwrap());

    assert!(keyexchange::decode_key_blob(&[]).is_err(), "empty");
    assert!(keyexchange::decode_key_blob(&good[..good.len() - 1]).is_err(), "truncated");
    for bad_version in [0x00u8, 0x01, 0x03, 0xff] {
        let mut x = good.clone(); x[0] = bad_version;
        assert!(keyexchange::decode_key_blob(&x).is_err(), "blob version 0x{bad_version:02x}");
    }
    let mut bad_role = good.clone(); bad_role[1] = 2;
    assert!(keyexchange::decode_key_blob(&bad_role).is_err(), "reserved role");
    let mut trailing = good.clone(); trailing.extend_from_slice(&[9, 9]);
    assert!(keyexchange::decode_key_blob(&trailing).is_err(), "trailing bytes");
    assert!(keyexchange::decode_key_blob(&vec![0u8; keyexchange::MAX_BLOB_BYTES + 1]).is_err(), "oversized");
}

#[test]
fn commitment_gate_rejects_substituted_key_material() {
    let v = vectors();
    let kx = &v["keyExchange"];
    let blob = unhex(kx["blobOfferHex"].as_str().unwrap());
    let commitment = descriptor::commit_blob(&blob);

    keyexchange::verify_blob_commitment(&blob, &commitment).expect("honest blob must pass");

    // A different blob — what an attacker able to rewrite the in-band frame but
    // not the scanned invitation would present.
    let other = unhex(kx["blobAnswerHex"].as_str().unwrap());
    assert!(keyexchange::verify_blob_commitment(&other, &commitment).is_err(), "substituted blob");

    // One flipped bit anywhere is enough.
    for idx in [0usize, 1, 5, 40, blob.len() - 1] {
        let mut t = blob.clone(); t[idx] ^= 0x01;
        assert!(keyexchange::verify_blob_commitment(&t, &commitment).is_err(), "blob byte {idx} flipped");
    }
    assert!(keyexchange::verify_blob_commitment(&blob, &[0u8; 8]).is_err(), "short commitment");
}

#[test]
fn transcript_covers_every_component() {
    let v = vectors();
    let kx = &v["keyExchange"];
    let od = unhex(v["descriptors"][0]["encodedHex"].as_str().unwrap());
    let ad = unhex(v["descriptors"][1]["encodedHex"].as_str().unwrap());
    let bo = unhex(kx["blobOfferHex"].as_str().unwrap());
    let ba = unhex(kx["blobAnswerHex"].as_str().unwrap());
    let shared = unhex(kx["sharedSecretHex"].as_str().unwrap());

    let base_t = keyexchange::build_transcript(&od, &ad, &bo, &ba).unwrap();
    let base_sas = keyexchange::compute_transcript_sas(&shared, &base_t).unwrap();
    let base_salt = keyexchange::derive_transcript_salt(&base_t);

    let mutate = |which: usize| {
        let (mut a, mut b, mut c, mut d) = (od.clone(), ad.clone(), bo.clone(), ba.clone());
        match which { 0 => a[6] ^= 0xff, 1 => b[6] ^= 0xff, 2 => c[10] ^= 0x01, _ => d[10] ^= 0x01 }
        keyexchange::build_transcript(&a, &b, &c, &d).unwrap()
    };
    for which in 0..4 {
        let t = mutate(which);
        assert_ne!(keyexchange::compute_transcript_sas(&shared, &t).unwrap(), base_sas,
                   "component {which}: the SAS must move");
        assert_ne!(keyexchange::derive_transcript_salt(&t), base_salt,
                   "component {which}: the salt must move");
    }

    // Role order, not call order.
    let swapped = keyexchange::build_transcript(&ad, &od, &ba, &bo).unwrap();
    assert_ne!(swapped, base_t, "the transcript is ordered by role");

    assert!(keyexchange::build_transcript(&od, &ad, &bo, &[]).is_err(), "incomplete transcript");
}
